name: tests
on:
    workflow_call:
        inputs:
            python-versions:
                required: true
                type: string
                default: '["3.12", "3.13"]'

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ${{ fromJson(inputs.python-versions) }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip setuptools wheel
                  pip install -e .[dev]
            - name: Run tox
              run: |
                  flake8
                  pytest --cov=hermes_client --cov-report=xml
            - name: Store the codecov report
              if: matrix.python-version == '3.12'
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-report
                  path: coverage.xml
                  overwrite: true
